<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2021-06-03T13:33:29" tests="0" file="cypress/integration/subFolder/reverse.calculator.ko.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="reverseCalculator" timestamp="2021-06-03T13:33:29" tests="1" time="0.0000" failures="1">
    <testcase name="reverseCalculator testFailure" time="0.0000" classname="testFailure">
      <failure message="expected 5 to equal 4" type="AssertionError"><![CDATA[AssertionError: expected 5 to equal 4
    at Context.eval (http://localhost:41213/__cypress/tests?p=cypress/integration/subFolder/reverse.calculator.ko.spec.js:104:19)]]></failure>
    </testcase>
  </testsuite>
</testsuites>